image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-Dsettings.security=.m2/security-settings.xml --settings .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test 

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests -P dist
  only:
    - master
