image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-Dsettings.security=.m2/settings-security.xml --settings .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

sonar:
  stage: build
  script:
    - mvn sonar:sonar -Dsonar.organization=muhammadkholidb-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=31356f328950346f28834ffbe4a7a9d90ddb8df6

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test 

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS javadoc:jar source:jar deploy -DskipTests -P dist
  only:
    - master
